background_opacity 0.7

foreground #bbdfd9
background #0e0e0e
selection_foreground #000000
selection_background #bbdfd9

color0  #2f4353
color1  #4f697c 
color2  #568c9f
color3  #699ba4
color4  #82a6aa
color5  #9dbbbb
color6  #9ec6c5 
color7  #bbdfd9

